### ISSUE TITLE
还是不行

### ISSUE THREAD

**Issue by powersee** [newchaos94/ptrss#1]
运行后显示这个

> xxx 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)

**Comment by newchaos94** [comment]
编码错误。有具体的报错位置？

**Comment by powersee** [comment]
没有，运行后就显示 yaml 文件里面的内容，然后就跟着显示这个
<img width="888" alt="QQ20190827-230524@2x" src="https://user-images.githubusercontent.com/38074760/63783215-2bf29c80-c91f-11e9-8437-86f3fb4de64c.png">

**Comment by newchaos94** [comment]
配置文件中，有【选填，默认】之类的，不设置就删掉这行，只是做提醒用的。不要有中文

**Comment by powersee** [comment]
这样，不过下午的时候也留着中文，可以正常的获取 rss 里面的内容，并显示出来，只是没有下载种子。

现在我就把中文都删除了，但是还是不行。
<img width="884" alt="QQ20190827-235118@2x" src="https://user-images.githubusercontent.com/38074760/63787126-df5e8f80-c925-11e9-82fb-d4206cfc9e5d.png">
我想问大佬你确实在你的 N1 上面成功运行了吗？我感觉都按你写的装了，怎么还是一直有问题呢。会不会有些我没装了，才导致这样的。

**Comment by newchaos94** [comment]
还是yaml问题，我重新修改了，你用新的试下，就该rss,cookie和download,其他不要改

**Comment by powersee** [comment]
<img width="886" alt="QQ20190828-001114@2x" src="https://user-images.githubusercontent.com/38074760/63788636-69a7f300-c928-11e9-8c17-9875d4a77926.png">

可以读取到信息了，但是没有下载

**Comment by newchaos94** [comment]
删除rss.db; 删除config.yaml中title和- 测试这两行(12,13行)；更新下ptrss.py; 
重新跑一次

**Comment by powersee** [comment]
<img width="887" alt="QQ20190828-002943@2x" src="https://user-images.githubusercontent.com/38074760/63789979-f9e73780-c92a-11e9-8594-8137daa5366d.png">
终于可以下载了，这样是否加 sleep 让它慢点下载就行了？

**Comment by newchaos94** [comment]
![3](https://user-images.githubusercontent.com/30197860/63790223-724df880-c92b-11e9-983b-7618355638fa.PNG)
已经加了1~4s随机sleep,可自行修改时长
